events {
    worker_connections 1024;
}

http {
    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    proxy_http_version  1.1;
    proxy_set_header    Host              $host;
    proxy_set_header    X-Real-IP         $remote_addr;
    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto https;
    proxy_set_header    Upgrade           $http_upgrade;
    proxy_set_header    Connection        $connection_upgrade;
    proxy_read_timeout  300s;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        location / {
            proxy_pass http://librenms:8000;
        }
    }

    server {
        listen 3000 ssl;
        location / {
            proxy_pass http://grafana:3000;
        }
    }

    server {
        listen 8080 ssl;
        location / {
            proxy_pass http://akvorado:8080;
        }
    }

    server {
        listen 8888 ssl;
        location / {
            proxy_pass http://oxidized:8888;
        }
    }
}
